### ISSUE TITLE
Decreasing health nerfs damage due to Configuration of GlassSoul mod

### ISSUE THREAD

**Issue by berylliumquestion** [ygsbzr/HollowKnight.FuryMod#1]
I'm making this issue as I've noticed there's a discrepancy between what damage should be and what it actually is. I started a new save and installed DebugMod to see what my damage is. Without the charm my damage against a Crawlid is 6. With the charm and this mod it decreases the masks to 1 and nerfs the damage down to 4 against a Crawlid

Sister issue here: https://github.com/Exempt-Medic/AlwaysFurious/issues/1

**Comment by ygsbzr** [comment]
Did you install other mod? Because the nail damage should be 5 in a new save,not 6

**Comment by ygsbzr** [comment]
If you install charmoverhaul,maybe they have conflict,because charmoverhaul modify many charms, include Fury

**Comment by berylliumquestion** [comment]
I will do some more testing and get back to you. But none of the mods I had installed advertised they change amount of damage output based on health

**Comment by berylliumquestion** [comment]
Mod by itself works on an absolute clean, other than DebugMod, install. Will try to figure out where incompatibility is coming from later on

**Comment by berylliumquestion** [comment]
It appears that the incompatibility is coming from GlassSoul. I have no idea why it interacts with this mod this way, but when it's enabled it changes the damage output of the player, at least from nail strikes. Due to my inability to read basic instructions I missed the part where the GlassSoul mod can be configured

**Comment by ygsbzr** [comment]
oh,I see that because glasssoul damage depend on you hp, naildamage will become your hp+1
so this mod will make your damage is (1+1)*1.75=4
